### ISSUE TITLE
Add config setting to enable/disable vehicle tilting

### ISSUE THREAD

**Issue by SirGlozz** [SBDPlugins/VehiclesPlus#102]
**Is your enhancement related to a problem? Please describe.**  
I wanted to disable tilting on vehicles, when we drive a helicopter, plane, boat or bike, those vehicles tilts on driving, and sometimes they look weird and laggy.

**Describe the solution you'd like**  
Add config option to enable/disable tilting, an optional config setting to make static vehicle models, like cars.
Something like:
`vehicleTilting: true/false`

**Additional context**  
Hope we can have this feature soon, thanks.
![image](https://user-images.githubusercontent.com/77519944/123518502-2b8ad000-d674-11eb-9c3a-cf99e015f8d1.png)

**Comment by stijnb1234** [comment]
You can create your own vehicle type with the API.

I will not and will never include a setting for this, because these settings are controlled in the `VehicleType`. It is not design-technically possible to change this without creating your own type.
