### ISSUE TITLE
Can't drive forward/afterward. Only twisting

### ISSUE THREAD

**Issue by Akmenis** [SBDPlugins/VehiclesPlus#104]
**Describe the bug**  
I can only twist in place, can't drive forward or afterward

**To Reproduce**  
1. Go to server on purpur engine
2. start it
3. try to move forward or afterward

**Expected behavior**  
If you do it great you shouldn't be able to drive forward or afterward.

**Screenshots or Video Recordings**  
If applicable, add screenshots or video recordings to help explain your problem.

**Server and Plugin Information**
 - Installed plugins:
 - VehiclesPlus Version:
 - Pro version
 - Server Platform and Version [eg: **PaperSpigot** 1.16.1 #135]: Purpur 1.16.5#395
 - Operating System (if applicable): Windows 10

**Additional context**  
Idk, i can't only drive straight./.. only twisting

**Comment by stijnb1234** [comment]
Please check our FAQ for creating an issue:
https://docs.volmit.com/vehiclesplus/faq#my-vehicles-wont-spawn-in-wont-move-are-invisible

This is NOT a bug in our plugin, but is caused by a setting in PaperSpigot and forks.

**Comment by Akmenis** [comment]
> Please check our FAQ before creating an issue:
> https://docs.volmit.com/vehiclesplus/faq#my-vehicles-wont-spawn-in-wont-move-are-invisible
> 
> This is NOT a bug in our plugin, but is caused by a setting in PaperSpigot and forks.

ahh, ok sorry i didn't seen FAQ

**Comment by stijnb1234** [comment]
> > Please check our FAQ before creating an issue:
> > https://docs.volmit.com/vehiclesplus/faq#my-vehicles-wont-spawn-in-wont-move-are-invisible
> > This is NOT a bug in our plugin, but is caused by a setting in PaperSpigot and forks.
> 
> ahh, ok sorry i didn't seen FAQ

No problem. Just a reminder for you and everyone else with this issue. 😉
