### ISSUE TITLE
Plugin Issue

### ISSUE THREAD

**Issue by PhrogiYT** [SBDPlugins/VehiclesPlus#107]
**Describe the bug**  
Plugin shows up as a red color and commands dont show up.

**Screenshots or Video Recordings**  
![image](https://user-images.githubusercontent.com/87917901/126883639-e398a4b0-b02a-4e42-bdfe-9263f1f647c8.png)

**Server and Plugin Information**
 - Installed plugins: Carz, dynmap, Harbor, holographic Displays, ImageOnMap, LuckPerms, Multiverse-Core, Protocolib, sethome, vault, VehiclesPlusPro, WorldEdit, World Guard.
 - VehiclesPlus Version: 2.3.0
 - Pro
 - PaperSpigot 1.17.1
 - Hosted on Aquatis

**Comment by stijnb1234** [comment]
You need an economy manager like Essentials.
