### ISSUE TITLE
Vehicles Permissions

### ISSUE THREAD

**Issue by pedroox2** [SBDPlugins/VehiclesPlus#108]
This feature was already requested from another user but i think that it has been forgotten.
The idea was to have more permissions for different types of vehicles, for example police cars, swats, paramedics or firefighters. The use of the plugin was for an RP server, and it was interesting to only have permissions for certain people, part of the emergency corps, to be able to obtain those vehicles, so that other people cannot have them.

In January it was to be added to the next release but I have not seen any trace of it. (https://github.com/SBDPlugins/VehiclesPlus/issues/36)

**Comment by stijnb1234** [comment]
You can already set the buy permission, so that players can only buy that specific vehicle if they have that permission. If you create permissions groups, then you can assign vehicles to groups of players.
