### ISSUE TITLE
Maximum height limit for flying vehicles

### ISSUE THREAD

**Issue by pandarua** [SBDPlugins/VehiclesPlus#110]
Is it possible to add a maximum height limit for flying vehicles so that players can't fly up indefinitely?
By the way, how long does recoding take to complete? We've been waiting for a long time.
Thank you.

**Comment by stijnb1234** [comment]
Not out of the box, possible with the API tho. Will add this in the recode.

Still planned, hoping mid to end Septembre.

**Comment by stijnb1234** [comment]
Implemented, will be added in the recode. ;)
