### ISSUE TITLE
NOT loading

### ISSUE THREAD

**Issue by SilverHammer09** [SBDPlugins/VehiclesPlus#112]
**Describe the bug**  
i start the server and my log goes Could not load 'plugins\VehiclesPlus-Pro-2.3.0.jar' in folder 'plugins'

**Expected behavior**  
me to play this on my new smp earth 2 server

**Server and Plugin Information**
 - Installed plugins: image on map and everything it said needed and essintlesX
 - VehiclesPlus Version: 2.3.0
 - Server Platform and Version [eg: **PaperSpigot** 1.16.1 #135]: paper

**Comment by stijnb1234** [comment]
Please provide my with your full startup logs.

**Comment by SilverHammer09** [comment]
im sorry im a big noob at tech stuff to you just want me to lik copy and past the whole thing or what again sorry

**Comment by stijnb1234** [comment]
> im sorry im a big noob at tech stuff to you just want me to lik copy and past the whole thing or what again sorry

Yes. Download the log file (logs/latest.log) AFTER you restarted the server and send it here.

**Comment by SilverHammer09** [comment]
[latest.log](https://github.com/SBDPlugins/VehiclesPlus/files/7146544/latest.log)
is this right?

**Comment by SilverHammer09** [comment]
did i do it wrong?

**Comment by SilverHammer09** [comment]
is there anything else you need from me?

**Comment by stijnb1234** [comment]
Please upgrade to Java 11 or higher.
