### ISSUE TITLE
Recode Enhancements (If not implemented already)

### ISSUE THREAD

**Issue by mesl** [SBDPlugins/VehiclesPlus#113]
So for the VehiclesPlus recode, Some features that would be interesting and helpful is a configurable storage platform, Like SQL, (SQLite or MySQL, etc) or the current data-folder structure but also a way to do everything by commands rather than the GUI so we can do things automated or for custom GUIs

Hope these features can get implemented
Kind regards, Merlyn

**Comment by stijnb1234** [comment]
Both are implemented!
