### ISSUE TITLE
question!

### ISSUE THREAD

**Issue by dinobossytnew** [SBDPlugins/VehiclesPlus#114]
I do not know if the plugin is still worked there is no discord or anything that motivates your purchase so I ask with your dev do you think it will return or this plugin is dead? 

Is it the same as the other devs who sell and abandon?

**Comment by AnnotationThomas** [comment]
There is a discord actually: https://discord.gg/R6ax6z2 
And yes they are still working on the plugin however, school and real life comes first. So yeah they are working on it in their spare time if they have any. On the other hand there are more plugins from them that require updates sometimes so it's not like VP is the only thing they work on.
