### ISSUE TITLE
[FEATURE] Public (non-owned) vehicles

### ISSUE THREAD

**Issue by ImFound** [SBDPlugins/VehiclesPlus#115]
**Is your feature request related to a problem? Please describe.**  
That's right, thanks to the API I'm trying to make a vehicle let's say public spawned every few minutes, except that it currently serves the owner of the vehicle.

**Describe the solution you'd like**  
I would like that you could (only via api) not have an owner of the vehicle, usable by everyone, blockable by everyone

**Describe alternatives you've considered**  
Making a bot that stays online 24/7 but would cost me too much

**Comment by stijnb1234** [comment]
Sounds like a good idea. Something was worked on for the old version, but was never implemented correctly. I will work on this for the recode. ;)

**Comment by ImFound** [comment]
Yeah, it's easy to make I think, you put a double constructor on spawnedvehicle class, and you put that if like playerUuid =  "" it don't add the vehicle to the garage and everyone can lock it or unlock it.

**Comment by stijnb1234** [comment]
Implemented! The recode now is based on the vehicles' UUID, and not on the player's UUID.

**Comment by ImFound** [comment]
:D waiting for the amazing update! <3
