### ISSUE TITLE
add VehicleLockEvent

### ISSUE THREAD

**Issue by ImFound** [SBDPlugins/VehiclesPlus#116]
**Is your feature request related to a problem? Please describe.**  
I need to check when a player locks a vehicle

**Describe the solution you'd like**  
an event api like "VehicleLockEvent"

**Describe alternatives you've considered**  
nothing

**Comment by stijnb1234** [comment]
Good idea! Will be implemented in the recode.

**Comment by stijnb1234** [comment]
The v3 now contains the VehicleLockStateChangedEvent!
