### ISSUE TITLE
Add support to Conxeptworks model engine

### ISSUE THREAD

**Issue by NFDCPP** [SBDPlugins/VehiclesPlus#117]
Please add support for ConxeptWorks model engine in VPRO3.0 (rewrite). This plugin will add the ability to open the door, open the window, raise the hood, spinning wheels or even water cannons in fire brigade vehicles, and it will add the ability to create advanced vehicle hitboxes and then there will be vehicle collisions.

I attach examples what you can add with this plugin, here's the link for this plugin https://www.spigotmc.org/resources/conxeptworks-model-engine—ultimate-custom-entity-model-manager-1-14-1-18.79477/ 

Attachments (in discord because github attachments won't work for me idk why):
https://cdn.discordapp.com/attachments/663549501503701013/935264430600642600/efs.mp4
https://cdn.discordapp.com/attachments/663549501503701013/935232585573994496/sfddrfgdf.mp4
https://cdn.discordapp.com/attachments/663549501503701013/935237681527554098/dgdrtgrt.mp4

**Comment by stijnb1234** [comment]
Sounds like a great concept. If I find the time to look into this plugin more, I think it can be a great feature for VehiclesPlus.

**Comment by stijnb1234** [comment]
This gets too complex for a simple plugin like VehiclesPlus.
