### ISSUE TITLE
1.18.2 Can't drive on Grass path blocks

### ISSUE THREAD

**Issue by ADM8** [SBDPlugins/VehiclesPlus#125]
Vehicles that drive over grass path blocks can't drive back onto normal blocks

To reproduce:
1. Drive on grass path blocks
2. stuck
3. agony

Drive over the blocks

**Server and Plugin Information**
 - Installed plugins: everything vehicleplus needs
 - VehiclesPlus Version:  Newest
 - Server Platform and Version : newest 1.18.2 paper jar

**Comment by stijnb1234** [comment]
Duplicate of #78

Those blocks have the same problem as slabs.
