### ISSUE TITLE
Vehicles being independent of economy

### ISSUE THREAD

**Issue by ADM8** [SBDPlugins/VehiclesPlus#126]
**Is your feature request related to a problem? Please describe.**  
I dislike being forced to use an enconomy plugin and feel it somewhat limits the scope this plugin could have since some servers don't use economy.

**Describe the solution you'd like**  
I would like there to be an option where you could disable garage and shop and instead just be able to spawn in vehicles standalone similar to how qav does it. Things like repairs, addons, and upgrades could perhaps also just be items you can hold in your hand and interact with vehicles instead of being forced to just spend money to get upgrade. Maybe the option for vehicles to be placed like spawn eggs. Could also be neat for there to be an assembly and disassembly time to prevent vehicle spam.

**Additional context**  
https://youtu.be/iziUG_Pglps
something like this is a bit like what I had in mind, this also somewhat shows off a cool way to do weapon support, I believe this server used crackshot combined with an unknown vehicle plugin. I suggest instead using weaponmechanics as it is the most modern and versatile solution when it comes to gun plugins.

**Comment by stijnb1234** [comment]
Implemented
