### ISSUE TITLE
vehicles with stages

### ISSUE THREAD

**Issue by pietrocervai** [SBDPlugins/VehiclesPlus#128]
to be able to create a vehicle that has stages, therefore without a driver.  to be able to get on it or you have to press on the vehicle or on a button next to it

**Comment by stijnb1234** [comment]
Like a metro or bus?

**Comment by pietrocervai** [comment]
> Like a metro or bus (public transport)?

yes

**Comment by stijnb1234** [comment]
That also means automatic (self) driving should be implemented, right?

**Comment by pietrocervai** [comment]
> That also means automatic (self) driving should be implemented, right?

yes

**Comment by stijnb1234** [comment]
Like the idea, but to complicated for now.
