### ISSUE TITLE
API Enhancement

### ISSUE THREAD

**Issue by QuenK30** [SBDPlugins/VehiclesPlus#129]
**Here are some proposals for the API:**

Be able to access the players garage

Be able to spawn vehicles directly from the player garage

See if a player has spawned his vehicle or not

Have a list of all spawn vehicles in the world

Have a list of all vehicles on the server

**Comment by stijnb1234** [comment]
> **Here are some proposals for the API:**
> 
> Be able to access the players garage
> 
> Be able to spawn vehicles directly from the player garage
> 
> See if a player has spawned his vehicle or not
> 
> Have a list of all spawn vehicles in the world
> 
> Have a list of all vehicles on the server

The player garage is already added to v3.
Spawn directly from garage; the garage contains vehicles with a spawn function.
Already possible
Already possible
Already possible
