### ISSUE TITLE
Giant models

### ISSUE THREAD

**Issue by SebxteR9** [SBDPlugins/VehiclesPlus#132]
what is the chance to add giant models? just swap armor stand for giant mob, it gives you many possibilities, much bigger models, you can then add big passenger planes

![image](https://user-images.githubusercontent.com/27051051/174480794-e9e322aa-62a6-433d-8453-aaf23553cede.png)

**Comment by stijnb1234** [comment]
Almost impossible to implement, because of the custom name and visiblity.
