### ISSUE TITLE
Geyser Compatibility

### ISSUE THREAD

**Issue by jcarney2024** [SBDPlugins/VehiclesPlus#139]
**Is your feature request related to a problem? Please describe.**  
I would like to suggest compatibility with Geyser MC (Bedrock Edition). Not related to a problem.

**Describe the solution you'd like**  
I would like you to create Bedrock resource packs, so vehicles will load properly in bedrock.

**Describe alternatives you've considered**  
There are no Geyser Compatible Vehicle plugins at the moment!

**Comment by Danieljunek17** [comment]
Well this is a nice idea, we will consider to do this but this won't be the first priority, it also doesn't help we don't create texture packs we outsource that part.

**Comment by stijnb1234** [comment]
I need to look into this. I'm unsure if its possible.

**Comment by stijnb1234** [comment]
Not possible because of ProtocolLib dependency for movement
