### ISSUE TITLE
CustomModelData for item

### ISSUE THREAD

**Issue by Collinvh** [SBDPlugins/VehiclesPlus#140]
**Is your enhancement related to a problem? Please describe.**  
I can't change the item to an custommodeldata because theirs currently not a way that I know of to do this

**Describe the solution you'd like**  
In the config of the vehicle to for the skin

**Additional context**  
![image](https://user-images.githubusercontent.com/18741445/214655197-213e02fe-3c0c-463f-b03b-bdf7e731d38d.png)

**Comment by stijnb1234** [comment]
```hjson
item:
{
  custommodeldata: 100
}
```
This works. Documentation on the options not added by default will follow ASAP.
