### ISSUE TITLE
Add more permissions

### ISSUE THREAD

**Issue by Serial23** [SBDPlugins/VehiclesPlus#61]
Add permissions for each things like for change owner, change name, for upgrade etc.

**Comment by Serial23** [comment]
?

**Comment by stijnb1234** [comment]
@relavis I've removed the issue template because it was filled in incorrectly. This one sentence describes the whole issue, so I don't think it's invalid.

**Comment by stijnb1234** [comment]
I am going to see what is possible with a recode.

**Comment by stijnb1234** [comment]
Added
