### ISSUE TITLE
Proposition of adding vehicle break (without blowing it out)

### ISSUE THREAD

**Issue by notFallingDevil** [SBDPlugins/VehiclesPlus#63]
REQUEST

**Describe the solution you'd like**  
Add an option to leave car health but remove blowing it up, like when health = 0 the car just can't ride and it stands in place until someone with vp.mechanic permission clicks on it with special item.

**Describe alternatives you've considered**  
NONE

**Additional context**  
Now the car blowups if you crash, it's so unrealistic! The car should stop in place until getting fixed!

**Comment by stijnb1234** [comment]
Will be added in the recode.

**Comment by stijnb1234** [comment]
Added
