### ISSUE TITLE
Add a permission to spawn specific vehicle type

### ISSUE THREAD

**Issue by Perrosovietico** [SBDPlugins/VehiclesPlus#87]
**Is your enhancement related to a problem? Please describe.**  
It would be nice if we could set a permission to spawn specific vehicle type, for example: "vp.spawn.examplecar", if you don't have that permission, you cannot spawn that car, but it will stay in your garage. 

**Describe the solution you'd like**  
Add the permission "vp.spawn.vehicle_name" just to allow the player spawn that vehicle if he have the permission.

**Additional context**  
I think it could be a nice idea, i already know that "vp.ride" permissions exists but driving and spawning are different.

**Comment by stijnb1234** [comment]
Good idea. That option is indeed missing. Will add. 👍

**Comment by stijnb1234** [comment]
Will be added in the recode.

**Comment by stijnb1234** [comment]
Added
