### ISSUE TITLE
Plugin Not loading/working

### ISSUE THREAD

**Issue by Akmenis** [SBDPlugins/VehiclesPlus#96]
Describe the bug
Plugin not loading (Version 2.3.0)

To Reproduce
idk, it is not loading

Expected behavior

Screenshots or Video Recordings
i don't have but it not loads (in log and commands not working)

Server and Plugin Information

Installed plugins: VehiclesPlus Pro v2.3.0, User login, SARanks, PluginConstructorAPI, QualityArmor, ItemBridge v2, TAB, HyperConomy (Economy plugin), Towny, CustomNukes, ProtocolLib, Vault, TimberPlugin, TownyChat, LogBlock, Dynmap-Towny, Dynmap, Brewery, Playerkits, SetHome, XWeatherPlus, Thirst, HeadsPlus, KelpEffect, RestartCountdown, AntyXray, GSit, Jobs, MySkin, NexEngine, GoldenCrates
VehiclesPlus Version:
Pro?
Server Platform and Version [eg: PaperSpigot 1.16.1 #135]: spigot 1.16.5
Operating System (if applicable): Windows
Additional context
LOG:https://pastebin.com/clone/hJUKRmTv . If it is possible please fix it as fast as you can.

**Comment by stijnb1234** [comment]
Please provide me startup logs, I can't help you with logs from Dynmap.
